version: 1.0.{build}
os: Visual Studio 2015 RC
build_script:
- dnvm upgrade
- dnu restore
artifacts:
- path: /AppOutput
  name: AppOutput
test_script:
- dnx.exe C:\projects\Building-Company-Rating-System-New\BCRS.Tests\project.json test -parallel none
